output:
  format: colored-line-number
  sort-results: true

linters:
  enable:
    - errname
    - errorlint
    - gocritic
    - goerr113
    - gofumpt
    - goheader
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - testpackage
    - thelper
    - typecheck

  disable-all: true

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  gofumpt:
    extra-rules: true

  goheader:
    values:
      const:
        COMPANY: z0ne
      regexp:
        FILE: "[a-zA-Z0-9_]+\\.go"
    template: |-
      {{ FILE }} Copyright (c) {{ YEAR }} {{ COMPANY }}.
      All Rights Reserved.
      Licensed under the Apache 2.0 License.
      See LICENSE the project root for license information.

      SPDX-License-Identifier: Apache-2.0

  govet:
    check-shadowing: true
    enable-all: true

  revive:
    rules:
      - name: add-constant
        arguments:
          - maxLitCount: "3"
            allowStrs: '""'
            allowInts: "0,1,2"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
      - name: argument-limit
        arguments: [4]
      - name: atomic
      - name: bare-return
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: cognitive-complexity
        arguments: [10]
      - name: comment-spacings
        arguments: []
      - name: confusing-naming
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: cyclomatic
        arguments: [10]
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: flag-parameter
      - name: function-result-limit
        arguments: [2]
      - name: function-length
        arguments: [50, 0]
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: imports-blacklist
        arguments:
          - "crypto/md5"
          - "crypto/sha1"
      - name: import-shadowing
      - name: line-length-limit
        arguments: [120]
      - name: max-public-structs
        arguments: [5]
      - name: time-equal
      - name: time-naming
      - name: var-naming
      - name: var-declaration
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: use-any
      - name: useless-break
      - name: waitgroup-by-value

issues:
  exclude-use-default: false
